//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class blogcomment
    {
        public long id { get; set; }
        public string comment { get; set; }
        public string name { get; set; }
        public System.DateTime postdate { get; set; }
        public long blog_id { get; set; }
    
        public virtual blog blog { get; set; }
    }
}
