//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogUserLike
    {
        public long IDBlog { get; set; }
        public long IDUser { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual blog blog { get; set; }
        public virtual user user { get; set; }
    }
}
