//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        public long id { get; set; }
        public string first_name { get; set; }
        public string description { get; set; }
        public Nullable<System.TimeSpan> start_time { get; set; }
        public Nullable<System.TimeSpan> end_time { get; set; }
        public Nullable<System.DateTime> requested_date { get; set; }
        public Nullable<decimal> cost_per_reservation { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<long> community_id { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<long> id_efac { get; set; }
    }
}
