//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public long id { get; set; }
        public long user_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string commentary { get; set; }
        public Nullable<int> assessment { get; set; }
        public Nullable<long> supplier_id { get; set; }
        public string user_name { get; set; }
    
        public virtual supplier supplier { get; set; }
    }
}
