//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public long id { get; set; }
        public long user_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string commentary { get; set; }
        public Nullable<int> assessment { get; set; }
        public Nullable<long> supplier_id { get; set; }
        public string user_name { get; set; }
    
        public virtual supplier supplier { get; set; }
    }
}
