//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contactinfo
    {
        public long id { get; set; }
        public string company_admin { get; set; }
        public string coordinator { get; set; }
        public string president { get; set; }
        public string vice_president { get; set; }
        public string treasurer { get; set; }
        public string secretary { get; set; }
        public string vocal1 { get; set; }
        public string vocal2 { get; set; }
        public string vocal3 { get; set; }
        public string phy_address { get; set; }
        public string postal_address { get; set; }
        public string phone_number1 { get; set; }
        public string phone_number2 { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<long> user_id { get; set; }
    }
}
