//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contactinfo
    {
        public long id { get; set; }
        public string company_admin { get; set; }
        public string coordinator { get; set; }
        public string president { get; set; }
        public string vice_president { get; set; }
        public string treasurer { get; set; }
        public string secretary { get; set; }
        public string vocal1 { get; set; }
        public string vocal2 { get; set; }
        public string vocal3 { get; set; }
        public string phy_address { get; set; }
        public string postal_address { get; set; }
        public string phone_number1 { get; set; }
        public string phone_number2 { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<long> user_id { get; set; }
        public Nullable<long> community_id { get; set; }
    }
}
