//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class creditcard
    {
        public long id { get; set; }
        public string first_name { get; set; }
        public string surname { get; set; }
        public string card_number { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
        public string ccv { get; set; }
        public string address { get; set; }
        public string country { get; set; }
        public string city { get; set; }
        public string phone { get; set; }
        public string state { get; set; }
        public string postal_code { get; set; }
        public long user_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual user user { get; set; }
    }
}
