//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class creditcard
    {
        public long id { get; set; }
        public string first_name { get; set; }
        public string surname { get; set; }
        public string card_number { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
        public string ccv { get; set; }
        public string address { get; set; }
        public string country { get; set; }
        public string city { get; set; }
        public string phone { get; set; }
        public string state { get; set; }
        public string postal_code { get; set; }
        public long user_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual user user { get; set; }
    }
}
