//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class document
    {
        public long id { get; set; }
        public string first_name { get; set; }
        public string uploaded_by { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public int type_id { get; set; }
        public string upload_document { get; set; }
        public Nullable<int> share { get; set; }
        public Nullable<bool> notify_email { get; set; }
        public Nullable<System.DateTime> uploaded_date { get; set; }
        public string link { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual document_type document_type { get; set; }
    }
}
