//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emailtheme
    {
        public long id { get; set; }
        public long user_id { get; set; }
        public string htmcontent { get; set; }
        public int type_id { get; set; }
    
        public virtual emailtype emailtype { get; set; }
        public virtual user user { get; set; }
    }
}
