//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class @event
    {
        public long id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string place { get; set; }
        public string description { get; set; }
        public string note { get; set; }
        public string name { get; set; }
        public System.DateTime event_date { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public int share { get; set; }
        public Nullable<bool> is_active { get; set; }
    }
}
