//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fee
    {
        public long id { get; set; }
        public string name { get; set; }
        public decimal cost { get; set; }
        public long bank_id { get; set; }
        public string merchant_account { get; set; }
        public System.DateTime created_at { get; set; }
        public long user_id { get; set; }
        public decimal tax_charge { get; set; }
        public decimal penalty { get; set; }
    
        public virtual bank bank { get; set; }
        public virtual user user { get; set; }
    }
}
