//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fee
    {
        public long id { get; set; }
        public string name { get; set; }
        public decimal cost { get; set; }
        public long bank_id { get; set; }
        public string merchant_account { get; set; }
        public System.DateTime created_at { get; set; }
        public long user_id { get; set; }
        public decimal tax_charge { get; set; }
        public decimal penalty { get; set; }
    
        public virtual bank bank { get; set; }
        public virtual user user { get; set; }
    }
}
