//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class friendmapping
    {
        public long id { get; set; }
        public long request_userid { get; set; }
        public long end_userid { get; set; }
        public string request_status { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public bool is_active { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
