//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class onlineuser
    {
        public long id { get; set; }
        public long user_id { get; set; }
        public string connectionID { get; set; }
        public bool is_online { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public bool is_active { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string user_img { get; set; }
    
        public virtual user user { get; set; }
    }
}
