//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class onlineuser
    {
        public long id { get; set; }
        public long user_id { get; set; }
        public string connectionID { get; set; }
        public bool is_online { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public bool is_active { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string user_img { get; set; }
    
        public virtual user user { get; set; }
    }
}
