//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public long id { get; set; }
        public Nullable<System.DateTime> date_issue { get; set; }
        public Nullable<System.DateTime> date_payment { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public string method { get; set; }
        public Nullable<bool> state { get; set; }
        public long user_id { get; set; }
        public long to_user_id { get; set; }
        public string first_name { get; set; }
        public string surname { get; set; }
        public string email { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
