//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class schedule
    {
        public int id { get; set; }
        public string schedule1 { get; set; }
        public Nullable<System.TimeSpan> from_time { get; set; }
        public Nullable<System.TimeSpan> to_time { get; set; }
    }
}
