//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class schedule
    {
        public int id { get; set; }
        public string schedule1 { get; set; }
        public Nullable<System.TimeSpan> from_time { get; set; }
        public Nullable<System.TimeSpan> to_time { get; set; }
    }
}
