//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class suscribe
    {
        public long id { get; set; }
        public string name { get; set; }
        public string last_name { get; set; }
        public string community_name { get; set; }
        public string address { get; set; }
        public string phone_number { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<bool> logged_in { get; set; }
        public long package_id { get; set; }
        public Nullable<bool> is_paid { get; set; }
        public Nullable<System.DateTime> paid_at { get; set; }
    
        public virtual package package { get; set; }
    }
}
