//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class suscribe
    {
        public long id { get; set; }
        public string name { get; set; }
        public string last_name { get; set; }
        public string community_name { get; set; }
        public string address { get; set; }
        public string phone_number { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<bool> logged_in { get; set; }
        public long package_id { get; set; }
        public Nullable<bool> is_paid { get; set; }
        public Nullable<System.DateTime> paid_at { get; set; }
    
        public virtual package package { get; set; }
    }
}
