//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Titulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Titulo()
        {
            this.Vehiculos = new HashSet<Vehiculo>();
        }
    
        public long Id { get; set; }
        public long IdUser { get; set; }
        public string upload_writing { get; set; }
        public string user_img { get; set; }
        public Nullable<bool> is_leased { get; set; }
        public Nullable<System.DateTime> since { get; set; }
        public Nullable<System.DateTime> until { get; set; }
        public string tenant_first_name1 { get; set; }
        public string tenant_last_name1 { get; set; }
        public string tenant_mother_last_name1 { get; set; }
        public string tenant_first_name2 { get; set; }
        public string tenant_last_name2 { get; set; }
        public string tenant_mother_last_name2 { get; set; }
        public string leased_postal_address { get; set; }
        public string leased_residential_address { get; set; }
        public string leased_upload_file { get; set; }
        public bool is_active { get; set; }
        public string siono { get; set; }
        public Nullable<long> create_userid { get; set; }
        public string apartment { get; set; }
        public System.DateTime acq_date { get; set; }
        public Nullable<bool> is_del { get; set; }
        public long IdCommunity { get; set; }
        public Nullable<int> CarMax { get; set; }
    
        public virtual community community { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehiculo> Vehiculos { get; set; }
    }
}
