//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Titulo
    {
        public long Id { get; set; }
        public long IdUser { get; set; }
        public string upload_writing { get; set; }
        public string user_img { get; set; }
        public Nullable<bool> is_leased { get; set; }
        public Nullable<System.DateTime> since { get; set; }
        public Nullable<System.DateTime> until { get; set; }
        public string tenant_first_name1 { get; set; }
        public string tenant_last_name1 { get; set; }
        public string tenant_mother_last_name1 { get; set; }
        public string tenant_first_name2 { get; set; }
        public string tenant_last_name2 { get; set; }
        public string tenant_mother_last_name2 { get; set; }
        public string leased_postal_address { get; set; }
        public string leased_residential_address { get; set; }
        public string leased_upload_file { get; set; }
        public bool is_active { get; set; }
        public string siono { get; set; }
        public Nullable<long> create_userid { get; set; }
        public string apartment { get; set; }
        public System.DateTime acq_date { get; set; }
    
        public virtual user user { get; set; }
    }
}
