//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tooltip
    {
        public int id { get; set; }
        public string watch1 { get; set; }
        public string edit1 { get; set; }
        public string remove1 { get; set; }
        public string reserve1 { get; set; }
        public string watch2 { get; set; }
        public string edit2 { get; set; }
        public string remove2 { get; set; }
        public string reserve2 { get; set; }
        public Nullable<int> user_type { get; set; }
    }
}
