//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tooltip
    {
        public int id { get; set; }
        public string watch1 { get; set; }
        public string edit1 { get; set; }
        public string remove1 { get; set; }
        public string reserve1 { get; set; }
        public string watch2 { get; set; }
        public string edit2 { get; set; }
        public string remove2 { get; set; }
        public string reserve2 { get; set; }
        public Nullable<int> user_type { get; set; }
    }
}
