//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        public long IdVehiculo { get; set; }
        public long IdTitulo { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string Color { get; set; }
        public int Year { get; set; }
        public string ClapBoard { get; set; }
        public string StampNumber { get; set; }
        public Nullable<bool> is_del { get; set; }
    
        public virtual Titulo Titulo { get; set; }
    }
}
